#!/bin/bash

# compilejava - Compiles and executes java program then deletes the class files
#
# Copyright Daniel Cranston 2008-2013
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This file is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this file. If not, see <http://www.gnu.org/licenses/>.

if [ $PS1 ]; then
   printf '%s\n' "compilejava: Please run as a subprocess" >&2
   return 10
fi

scriptName="$(basename "$0")"

if ( ! which java javac &> /dev/null ); then
   printf '%s\n' "$scriptName: Dependencies not found" >&2
   exit 20
fi

#To fix: pattern matching in brackets
#if ! [ -a *.java ]; then
#   printf '%s\n' "$scriptName: no .java files found" >&2
#   exit 50
#fi

rm *.class 2> /dev/null

javac *.java && java "$@"

rm *.class 2> /dev/null

exit
